# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               'Dr V Gladkova'
tagline:             'mathematician etc.'
description:         'Not much here yet but will keep updating'
url:                 'http://valglad.github.io'
baseurl:             '/gsoc/' # blog path
gems:                [jekyll-paginate,jekyll-feed]
paginate:            5
paginate_path:       '/gsoc/:num/'

# About/contact
author:
  name:              V Gladkova
  url:               
  email:

# Custom vars
version:             1.0.0
